<?xml version="1.0"?>
<!-- Copyright (c) 2016 The UUV Simulator Authors.
     All rights reserved.

     Licensed under the Apache License, Version 2.0 (the "License");
     you may not use this file except in compliance with the License.
     You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing, software
     distributed under the License is distributed on an "AS IS" BASIS,
     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     See the License for the specific language governing permissions and
     limitations under the License.
-->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
  <!-- Import macro files -->
  <!--  <xacro:include filename="$(find uuv_descriptions)/models/common/urdf/common.urdf.xacro" />-->
    <xacro:include filename="$(find uuv_descriptions)/urdf/common.urdf.xacro" />
  <xacro:include filename="$(find uuv_sensor_ros_plugins)/urdf/sensor_snippets.xacro"/>
  <xacro:include filename="$(find uuv_gazebo_ros_plugins)/urdf/snippets.xacro"/>
  <!-- Properties -->
  <xacro:property name="mass" value="69.7"/>
  <xacro:property name="length" value="1.98"/>
  <xacro:property name="diameter" value="0.23"/>
  <xacro:property name="radius" value="${diameter*0.5}"/>
  <xacro:property name="volume" value="0.06799987704121499"/>
  <xacro:property name="cob" value="0 0 0.06"/>
  <xacro:property name="rho" value="1027.0"/>

  <xacro:property name="area" value="0.04155"/>
  <xacro:property name="length" value="1.98"/>

  <xacro:property name="visual_mesh_file" value="file://$(find nopp_gazebo)/mesh/aug.dae"/>
  <xacro:property name="collision_mesh_file" value="file://$(find nopp_gazebo)/mesh/aug.dae"/>

  <xacro:macro name="aug_base" params="namespace debug inertial_reference_frame">
    <link name="${namespace}/base_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="${visual_mesh_file}" scale="0.03 0.03 0.03" />
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="${visual_mesh_file}" scale="0.1 0.1 0.1" />
        </geometry>
      </collision>

      <inertial>
        <mass value="${mass}" />
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.6" ixy="0" ixz="0"
                 iyy="30.0" iyz="0"
                 izz="35.0" />
      </inertial>
    </link>

    
  </xacro:macro>
</robot>
